### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by marcuslib** [giovanne123/Ecoflow_Powerstream_HomeAssistant_Automation_Documentation#1]
Hiya,

I keep trying different ways and keep getting "Not found" when running the below

http://192.168.87.80:8000/cmd?token_key=token_value&ac_output_watt=150

I have copied files to c:\ecoflow folder

I have updated env file to

NODE_ENV=development
KEY_MAIL=[my_email@email.com](mailto:my_email@email.com)
KEY_URL=cmd
KEY_PASSWORD=Password - correct password with no quotes or spaces etc
KEY_POWERSTREAM_SN=HW51ZEH4SF5XXXXXX - My correct serial taken from the app, also works in HA with [hassio-ecoflow-cloud
KEY_QUERY_AC=100
KEY_QUERY_PRIO=0
TOKEN=token_key
TOKEN_VAL=token_value
TARGET=2

in CMD I run

node C:\ecoflow\server.js
27/11/2023 16:13:14: Starting app listening at port 8000 -------------------- sticks on this

**Comment by giovanne123** [comment]
Handled in origin repo -> https://github.com/bogdancs92/ecoflow-powerstream-nodejs/issues/3
